name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ec2_instance: 
          - { host: ${{ secrets.EC2_HOST_1 }}, user: ${{ secrets.EC2_USER }}, key: ${{ secrets.EC2_KEY }} }
          - { host: ${{ secrets.EC2_HOST_2 }}, user: ${{ secrets.EC2_USER }}, key: ${{ secrets.EC2_KEY }} }

    steps:
    - name: SSH and deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ matrix.ec2_instance.host }}
        username: ${{ matrix.ec2_instance.user }}
        key: ${{ matrix.ec2_instance.key }}
        script: |
          docker pull kesleylin2000/wits_inventory_management:latest
          docker stop wits_inventory_management_1 || true
          docker rm wits_inventory_management_1 || true
          docker run -d -p 8080:8080 --name wits_inventory_management_1 --restart unless-stopped kesleylin2000/wits_inventory_management:latest
