name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ec2_instance: 
          - host: "EC2_HOST_1"
            user: "EC2_USER"
            key: "EC2_KEY"
          - host: "EC2_HOST_2"
            user: "EC2_USER"
            key: "EC2_KEY"

    steps:
    - name: SSH and deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets[matrix.ec2_instance.host] }}
        username: ${{ secrets[matrix.ec2_instance.user] }}
        key: ${{ secrets[matrix.ec2_instance.key] }}
        script: |
          docker pull kesleylin2000/wits_inventory_management:latest
          docker stop wits_inventory_management_1 || true
          docker rm wits_inventory_management_1 || true
          docker run -d -p 8080:8080 --name wits_inventory_management_1 \
            --restart unless-stopped \
            -e DB_URL=${{ secrets.DB_URL }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            kesleylin2000/wits_inventory_management:latest